# Site settings
title: Serene Audio Inc.
email: info@sereneaudio.com
description: > # this means to ignore newlines until "baseurl:"
    Serene Audio brings sublime musical experiences
    to your environment through making truly high fidelity and
    beautifully crafted speakers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sereneaudio.com" # the base hostname & protocol for your site
twitter_username: sereneaudio
github_username:  sereneaudio

# Build settings
markdown: kramdown
permalink: /blog/:title
gems:
- jekyll-sitemap
